@startuml

skinparam nodesep 100
/'skinparam ranksep 200'/

left header
Class diagram: Main View
endheader

title Class diagram: Main View

/' Define the dependencies
Entry <|-- ToDo
'/


/' Define the class details'/

package vaadin {
}

package GUI {
    class MainView {
    settingsButton
    calendarButton
    mainButton
    tipButton
    header("despresso")
    __
    + addListener()
    }

    class HomeView {
    taskConfirmButton
    moodSlider
    + updateNextTask()
    }

    class SettingsView {
    + addListener()
    }
    class CalendarView {
    + addListener()
    }
    class MoodView {
    + addListener()
    }
    class TipView {
    + addListener()
    }
}

package Presentation {
    class MainPresenter{
    + showSettingsView()
    + showTipView()
    + showCalendarView()
    + showMoodView()
    + taskConfirmButtonClick()
    }

    class HomePresenter {
    + showHomeView()
    }

    class SettingsPresenter {
    + showSettingsView()
    }
    class CalendarPresenter {
    + showCalendarView()
    }
    class TipPresenter {
    + showTipView()
    }
    class MoodPresenter {
    + showMoodView()
    }
}

package Logic {
    class MainModel {
    Calendar
    + updateTaskConfirmed()
    }

    class Calendar {
    List calendarEntries
    + getNextEntry()
    }

    class CalendarEntry {
    }
}

/' Define entity relations (?)'/

vaadin <. GUI

MainPresenter "1" -- "1" MainView
MainPresenter "1" -> "1" SettingsPresenter
MainPresenter "1" -> "1" CalendarPresenter
MainPresenter "1" -> "1" TipPresenter
MainPresenter "1" -> "1" MoodPresenter
SettingsView "1" -- "1" SettingsPresenter
HomeView "1" --> "1" HomePresenter
Calendar "1" -> "n" CalendarEntry
TipView "1" -- "1" TipPresenter
CalendarView "1" -- "1" CalendarPresenter
MoodView "1" -- "1" MoodPresenter
HomePresenter "1" - MainPresenter

MainPresenter "1" -- "1" MainModel

MainModel "1" -> "1" Calendar

@enduml