@startuml

skinparam nodesep 100
skinparam ranksep 40

title Class diagram: despresso

/' Define the class details'/

package vaadin {
}

package view {
    interface SubjectInterface

    class SettingsViewImpl {
    + addListener()
    }
    class CalendarViewImpl {
    + addListener()
    }
    class MoodViewImpl {
    + addListener()
    }
    class TipsViewImpl {
    + addListener()
    }
    class HomeViewImpl {
        Slider: moodSlider
        Label: nextTask
        Button: nextTaskDone
        + updateNextTask()
        }
    class MainViewImpl {
        Button: home
        header("despresso")
        Button: settings
        ..
        Button: mood
        Button: calendar
        Button: tips
        __
        + addListener()
        }
}

package presenter {
    interface ObserverInterface
    interface MoodObserverInterface
    interface TipObserverInterface
    interface MainObserverInterface
    interface CalendarObserverInterface
    interface SettingsObserverInterface
    interface HomeObserverInterface

    class MainPresenter{
    + showHomeView()
    + showSettingsView()
    + showMoodView()
    + showCalendarView()
    + showTipsView()
    }

    class HomePresenter {
    + showHomeView()
    + confirmNextTask()
    + saveMoodEntry()
    }

    class SettingsPresenter {
    + showSettingsView()
    }
    class CalendarPresenter {
    + showCalendarView()
    }
    class TipPresenter {
    + showTipsView()
    }
    class MoodPresenter {
    + showMoodView()
    }
}

package logic {
    class MainModel {
    Calendar
    + updateTaskConfirmed()
    }

    class CalendarModel {
    List: calendarEntries
    + getNextEntry()
    }

    class MoodModel

    class TipModel

    class SettingsModel

    class HomeModel

    class CalendarEntry
}

package persistence {

    interface RepositoryInterface

    class TipRepository

    class CalendarRepository

    class MoodRepository

}
  package database <<Database>> {
    }



/' Define relations'/

vaadin <.. view

/' Presenter - View'/
MainPresenter "1" -- "1" MainViewImpl
SettingsViewImpl "1" -- "1" SettingsPresenter
HomeViewImpl "1" -- "1" HomePresenter
TipsViewImpl "1" -- "1" TipPresenter
CalendarViewImpl "1" -- "1" CalendarPresenter
MoodViewImpl "1" -- "1" MoodPresenter

/' View - View'/
MainViewImpl "1" -> "1" HomeViewImpl
MainViewImpl "1" -> "1" SettingsViewImpl
MainViewImpl "1" -> "1" CalendarViewImpl
MainViewImpl "1" -> "1" TipsViewImpl
MainViewImpl "1" -> "1" MoodViewImpl

/' Presenter - Model'/
MainPresenter "1" -- "1" MainModel
TipPresenter "1" -- "1" TipModel
MoodPresenter "1" -- "1" MoodModel
SettingsPresenter "1" -- "1" SettingsModel
HomePresenter "1" -- "1" HomeModel
CalendarPresenter "1" -- "1" CalendarModel


CalendarModel "1" -> "n" CalendarEntry

MainModel "1" -> "1" CalendarModel

SubjectInterface <|-- MainViewImpl
SubjectInterface <|-- MoodViewImpl
SubjectInterface <|-- TipsViewImpl
SubjectInterface <|-- CalendarViewImpl
SubjectInterface <|-- SettingsViewImpl
SubjectInterface <|-- HomeViewImpl


ObserverInterface <|-- MainObserverInterface
ObserverInterface <|-- MoodObserverInterface
ObserverInterface <|-- TipObserverInterface
ObserverInterface <|-- HomeObserverInterface
ObserverInterface <|-- CalendarObserverInterface
ObserverInterface <|-- SettingsObserverInterface

MainObserverInterface <|-- MainPresenter
MoodObserverInterface <|-- MoodPresenter
TipObserverInterface <|-- TipPresenter
HomeObserverInterface <|-- CalendarPresenter
CalendarObserverInterface <|-- SettingsPresenter
SettingsObserverInterface <|-- HomePresenter

/' Persistence '/
RepositoryInterface <|-- TipRepository
RepositoryInterface <|-- CalendarRepository
RepositoryInterface <|-- MoodRepository
TipModel --> TipRepository
MoodModel --> MoodRepository
CalendarModel --> CalendarRepository

CalendarRepository --> database
MoodRepository --> database
TipRepository --> database

@enduml