@startuml

skinparam nodesep 100

actor User


package "Client" {
node Browser

}

package "Server" {

node webServ1 [
Web Application Server
(Jetty)
]

interface "Web Interface" as webint
interface "DB Interface" as dbint

database db1[
SQLite
(Memory DB)
]
}

User -- Browser
Browser - webint
webint - webServ1
webServ1 -- dbint
dbint -- db1

@enduml
